In [1]:
import torch

x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]


tensor(3)

In [4]:
len(x)

4

In [5]:
x.shape

torch.Size([4])

In [7]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [18]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
C=A

In [21]:
print(id(A)==id(B))
id(A)==id(C)

False


True

In [22]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [23]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [24]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [28]:
A=torch.arange(20*2).reshape(2,5,4)
print(A)
A.shape, A.sum()

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])


(torch.Size([2, 5, 4]), tensor(780))

In [30]:
A_sum_axis0=A.sum(axis=2)
A_sum_axis0, A_sum_axis0.shape

(tensor([[  6,  22,  38,  54,  70],
         [ 86, 102, 118, 134, 150]]),
 torch.Size([2, 5]))

In [35]:
print(A)
sum_A=A.sum(axis=2,keepdims=True)
sum_A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])


tensor([[[  6],
         [ 22],
         [ 38],
         [ 54],
         [ 70]],

        [[ 86],
         [102],
         [118],
         [134],
         [150]]])

In [36]:
A.cumsum(axis=1)

tensor([[[  0,   1,   2,   3],
         [  4,   6,   8,  10],
         [ 12,  15,  18,  21],
         [ 24,  28,  32,  36],
         [ 40,  45,  50,  55]],

        [[ 20,  21,  22,  23],
         [ 44,  46,  48,  50],
         [ 72,  75,  78,  81],
         [104, 108, 112, 116],
         [140, 145, 150, 155]]])

In [37]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [50]:
A=torch.arange(20,dtype=float).reshape(5,4)
x=torch.arange(4,dtype=float)
print(A)
print(x)
A.shape, x.shape, torch.mv(A,x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=torch.float64)
tensor([0., 1., 2., 3.], dtype=torch.float64)


(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.], dtype=torch.float64))