In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super(CenteredLayer, self).__init__()

    def forward(self, x):
        return x - x.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y=net(torch.rand(4, 8))
Y.mean()

tensor(6.9849e-09, grad_fn=<MeanBackward0>)

In [3]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super(MyLinear, self).__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.8868,  0.6452, -0.1346],
        [ 1.0522,  1.7584,  0.5169],
        [-0.6238,  1.1870,  0.7768],
        [-0.2126,  0.5339,  0.9953],
        [ 0.2235,  0.4562,  0.9973]], requires_grad=True)

In [4]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.5670, 0.9664],
        [0.0000, 1.6364, 1.1419]])

In [5]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[ 5.4416],
        [12.6451]])